[/Script/GameplayTags.GameplayTagsSettings]

; === 1. ROZMIAR I GABARYTY PROPÓW ===
GameplayTagList=(Tag="Prop.Size.Small",Comment="Maly rekwizyt fizyczny (puszki, butelki) - do kopania nogą")
GameplayTagList=(Tag="Prop.Size.Medium",Comment="Sredni rekwizyt (krzesła, małe skrzynki) - do barykadowania")
GameplayTagList=(Tag="Prop.Size.Heavy",Comment="Ciezki rekwizyt (pancerne szafy, wielkie skrzynki) - wymaga Wigoru")

; === 2. STATUSY I URAZY POSTACI (Vitals / Debuffy) ===
GameplayTagList=(Tag="Status.Injury.Minor.Sprain",Comment="Drobny uraz: skręcenie / wolniejszy chód")
GameplayTagList=(Tag="Status.Injury.Major.Legs",Comment="Krytyczny uraz: uszkodzenie nóg - brak skoku i sprintu")
GameplayTagList=(Tag="Status.Madness.Scotophobia",Comment="Atak szaleństwa: fobia ciemności")
GameplayTagList=(Tag="Status.Madness.Paranoia",Comment="Atak szaleństwa: fałszywe dźwięki słuchu 3D")

; === 3. KLUCZE I METROIDVANIA ===
GameplayTagList=(Tag="Key.Brass",Comment="Mosiezny klucz do drzwi")
GameplayTagList=(Tag="Key.Iron",Comment="Zelazny klucz")